import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    copyright: {
        top: 2,
        textAlign: 'center',
        color: '#3e3e3e',
        fontSize: 8,
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        marginHorizontal: 10,
        marginBottom: 10,
        color: '#c5c5c5',
    },
    instructions: {
        textAlign: 'center',
        color: '#c5c5c5',
        marginBottom: 5,
        fontSize: 12,
        paddingHorizontal: 20,
    },
    disclaimTitle: {
        textAlign: 'center',
        color: '#5b5b5b',
        marginTop: 10,
        fontWeight: 'bold',
        fontSize: 9,
        marginBottom: 5,
        paddingHorizontal: 20,
    },
    disclaimText: {
        color: '#5b5b5b',
        textAlign: 'justify',
        fontSize: 8,
        marginBottom: 5,
        paddingHorizontal: 20,
    },
    subtext: {
        textAlign: 'center',
        color: '#e7d903',
        marginBottom: 5,
    },
    button: {
        alignItems: 'center',
        backgroundColor: '#988c03',
        padding: 10,
        height: 50,
    },
    screenContent: {
        backgroundColor: '#2d2d2d',
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    inputLine: {
        width: '30%',
        backgroundColor: 'rgba(79,74,66,0.49)',
        borderRadius: 20,
        height: 50,
        fontSize: 12,
        textAlign:'center',
        marginTop: 10,
        borderWidth: 2,
        borderColor: '#09ff05',
        color: '#fff'
    },
    inputWrapper: {
        width: '50%',
    },
    patternButton: {
        borderColor: '#19869c',
        borderWidth: 2,
        borderRadius: 20,
        width: 300,
        elevation: 8,
        backgroundColor: '#2d2d2d',
        height: 40,
    },
    patternButtonText: {
        color: '#74faff',
        textAlign: 'center',
        justifyContent: 'center',
        padding: 8,
        fontSize: 12,
    },
    buttonDescription: {
        color: '#1da0ba',
        width: '80%',
        textAlign: 'center',
        marginTop: 10,
        fontSize: 10,
        padding: 5,
    },
    pattScreenContent: {
        backgroundColor: '#2d2d2d',
        flex: 1,
    },
    pattrnNum: {
        color: '#E0B90D',
        textAlign: 'center',
        padding: 10,
    },
    pattDescript: {
        width: '30%',
        height: 30,
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#e0b90d',
        borderRadius: 20,
        backgroundColor: 'rgba(45,45,45,0.35)',
        shadowColor: '#1a192c',
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        marginTop: 10,
        position: 'absolute',
        top: 5,
        right: 10,
        justifyContent: 'center',
        zIndex: 10,
    },
    rmDescript: {
        width: '30%',
        height: 30,
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#1DA0BA',
        borderRadius: 20,
        backgroundColor: 'rgba(45,45,45,0.35)',
        shadowColor: '#1a192c',
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        marginTop: 10,
        position: 'absolute',
        top: 5,
        right: 10,
        justifyContent: 'center',
        zIndex: 10,
    },
    dayPatNum: {
        backgroundColor: '#4b4b4b',
        marginRight: 7,
        padding: 5,
        borderColor: '#52e5eb',
        borderWidth: 2,
        borderRadius: 5,
        width: '15%',
        color: '#fff',
    },
});

export default styles;